/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GhanaDayRouteImport } from './routes/ghana-day'
import { Route as EnsembleRouteImport } from './routes/ensemble'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPressKitRouteImport } from './routes/admin.press-kit'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEnsembleRouteImport } from './routes/admin.ensemble'
import { Route as AdminAwardsRouteImport } from './routes/admin.awards'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GhanaDayRoute = GhanaDayRouteImport.update({
  id: '/ghana-day',
  path: '/ghana-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsembleRoute = EnsembleRouteImport.update({
  id: '/ensemble',
  path: '/ensemble',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPressKitRoute = AdminPressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnsembleRoute = AdminEnsembleRouteImport.update({
  id: '/ensemble',
  path: '/ensemble',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/ensemble': typeof EnsembleRoute
  '/ghana-day': typeof GhanaDayRoute
  '/media': typeof MediaRoute
  '/support': typeof SupportRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/ensemble': typeof AdminEnsembleRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/press-kit': typeof AdminPressKitRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/ensemble': typeof EnsembleRoute
  '/ghana-day': typeof GhanaDayRoute
  '/media': typeof MediaRoute
  '/support': typeof SupportRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/ensemble': typeof AdminEnsembleRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/press-kit': typeof AdminPressKitRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/ensemble': typeof EnsembleRoute
  '/ghana-day': typeof GhanaDayRoute
  '/media': typeof MediaRoute
  '/support': typeof SupportRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/ensemble': typeof AdminEnsembleRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/press-kit': typeof AdminPressKitRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/awards'
    | '/contact'
    | '/ensemble'
    | '/ghana-day'
    | '/media'
    | '/support'
    | '/admin/awards'
    | '/admin/ensemble'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/media'
    | '/admin/press-kit'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/contact'
    | '/ensemble'
    | '/ghana-day'
    | '/media'
    | '/support'
    | '/admin/awards'
    | '/admin/ensemble'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/media'
    | '/admin/press-kit'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/awards'
    | '/contact'
    | '/ensemble'
    | '/ghana-day'
    | '/media'
    | '/support'
    | '/admin/awards'
    | '/admin/ensemble'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/media'
    | '/admin/press-kit'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  ContactRoute: typeof ContactRoute
  EnsembleRoute: typeof EnsembleRoute
  GhanaDayRoute: typeof GhanaDayRoute
  MediaRoute: typeof MediaRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghana-day': {
      id: '/ghana-day'
      path: '/ghana-day'
      fullPath: '/ghana-day'
      preLoaderRoute: typeof GhanaDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensemble': {
      id: '/ensemble'
      path: '/ensemble'
      fullPath: '/ensemble'
      preLoaderRoute: typeof EnsembleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/press-kit': {
      id: '/admin/press-kit'
      path: '/press-kit'
      fullPath: '/admin/press-kit'
      preLoaderRoute: typeof AdminPressKitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ensemble': {
      id: '/admin/ensemble'
      path: '/ensemble'
      fullPath: '/admin/ensemble'
      preLoaderRoute: typeof AdminEnsembleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminEnsembleRoute: typeof AdminEnsembleRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPressKitRoute: typeof AdminPressKitRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAwardsRoute: AdminAwardsRoute,
  AdminEnsembleRoute: AdminEnsembleRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPressKitRoute: AdminPressKitRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AwardsRoute: AwardsRoute,
  ContactRoute: ContactRoute,
  EnsembleRoute: EnsembleRoute,
  GhanaDayRoute: GhanaDayRoute,
  MediaRoute: MediaRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
